// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 95d259bbadaa

package invoicesv2

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createLineItemCmdMeta = []flagutil.FlagMeta{
	{FlagName: "idempotency-key", Shorthand: "i", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional idempotency key. If provided, duplicate requests with the same key return the previously created item."},
	{FlagName: "body-param.subscription-id", FieldPath: "Body.SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "The subscription ID. Exactly one of subscriptionId or invoiceId must be provided."},
	{FlagName: "body-param.invoice-id", FieldPath: "Body.InvoiceID", Kind: flagutil.FlagKindString, Optional: true, Description: "The invoice ID to attach this item directly to. Exactly one of subscriptionId or invoiceId must be provided. The invoice must be in ACTIVE or CLOSING state."},
	{FlagName: "body-param.display-name", FieldPath: "Body.DisplayName", Kind: flagutil.FlagKindString, Required: true, Description: "Human-readable label shown on the invoice. [required]"},
	{FlagName: "body-param.description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "Optional longer description shown on the invoice."},
	{FlagName: "body-param.currency", FieldPath: "Body.Currency", Kind: flagutil.FlagKindString, Required: true, Description: "ISO 4217 currency code (e.g., USD). Must match the subscription or invoice currency. [required]"},
	{FlagName: "body-param.quantity", FieldPath: "Body.Quantity", Kind: flagutil.FlagKindFloat64, Required: true, Description: "Number of units. [required]"},
	{FlagName: "body-param.unit-price", FieldPath: "Body.UnitPrice", Kind: flagutil.FlagKindFloat64, Required: true, Description: "Price per unit as a decimal amount (e.g., 29.99 for $29.99). Can be negative for credits or adjustments. [required]"},
	{FlagName: "body-param.invoice-at", FieldPath: "Body.InvoiceAt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"invoiceAt,omitempty"`, Description: "When to collect this item into an invoice. Defaults to now. Ignored when invoiceId is provided."},
	{FlagName: "body-param.period-start", FieldPath: "Body.PeriodStart", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"periodStart,omitempty"`, Description: "Start of the billing period for display purposes. Defaults to now."},
	{FlagName: "body-param.period-end", FieldPath: "Body.PeriodEnd", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"periodEnd,omitempty"`, Description: "End of the billing period for display purposes. Defaults to now."},
	{FlagName: "body-param.idempotency-key", FieldPath: "Body.IdempotencyKey", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"idempotencyKey,omitempty"`, Description: "Optional caller-provided idempotency key. Auto-generated if not provided."},
}

// initCreateLineItemCmd initializes the create-line-item command.
func initCreateLineItemCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-line-item",
		Short:   "Create Manual Line Item",
		Long:    "Create a manual line item for a billing v1 subscription. Manual line items are ad-hoc charges or credits that flow through the same collection pipeline as auto-generated items. Exactly one of subscriptionId or invoiceId must be provided.",
		Example: "  paygentic invoices-v2 create-line-item --body-param.display-name Nathan54 --body-param.currency Rwanda Franc --body-param.quantity 6214.31 --body-param.unit-price 7408.13",
		RunE:    runCreateLineItemCmd,
		Aliases: []string{"cli"},
	}
	flagutil.RegisterFlags(cmd, createLineItemCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateLineItemRequest](createLineItemCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-line-item: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateLineItemCmd executes the create-line-item command.
func runCreateLineItemCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createLineItemCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createLineItemCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateLineItemRequest](cmd, createLineItemCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InvoicesV2.CreateLineItem(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
