// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: dad0037073fa

package invoicesv2

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var downloadInvoicePdfCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The invoice ID [required]"},
}

// initDownloadInvoicePdfCmd initializes the download-invoice-pdf command.
func initDownloadInvoicePdfCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "download-invoice-pdf",
		Short:   "Download Invoice PDF",
		Long:    "Downloads the Paygentic-rendered invoice document. The caller must be authenticated and entitled to the invoice; the stored document is streamed back, so no storage URL is ever handed out. Returns 404 when the invoice's document is the tax provider's rather than ours — in that case the invoice resource reports pdfSource `tax_provider` and its pdfUrl points at the provider's link instead.\n\nThis operation returns binary data. Use --output-file <path> to save to a file, or pipe the output to another command.",
		Example: "  paygentic invoices-v2 download-invoice-pdf --id <id>",
		RunE:    runDownloadInvoicePdfCmd,
		Aliases: []string{"dip"},
	}
	flagutil.RegisterFlags(cmd, downloadInvoicePdfCmdMeta)
	if err := flagutil.ValidateMeta[operations.DownloadInvoicePdfRequest](downloadInvoicePdfCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for download-invoice-pdf: %w", err)
	}
	cmd.Flags().String("output-file", "", "Save the response body to a file path (recommended for binary/file responses)")
	cmd.Flags().Bool("output-b64", false, "Encode binary response as base64 and print to stdout")
	cmd.MarkFlagFilename("output-file")
	parent.AddCommand(cmd)
	return nil
}

// runDownloadInvoicePdfCmd executes the download-invoice-pdf command.
func runDownloadInvoicePdfCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, downloadInvoicePdfCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, downloadInvoicePdfCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DownloadInvoicePdfRequest](cmd, downloadInvoicePdfCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	res, err := s.InvoicesV2.DownloadInvoicePdf(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}
	if outputFile, _ := flagutil.GetStringFlag(cmd, "output-file"); outputFile != "" {
		return output.WriteToFile(cmd, res, outputFile)
	}
	if outputB64, _ := flagutil.GetBoolFlag(cmd, "output-b64"); outputB64 {
		return output.WriteBase64(cmd, res)
	}
	if output.IsBinaryTTYBlocked(cmd, res) {
		return fmt.Errorf("binary response cannot be written to a terminal; use --output-file <path>, --output-b64, or pipe to another command")
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
