// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package invoicesv2

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listLineItemsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "subscription-id", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by subscription ID. At least one of subscriptionId or invoiceId must be provided."},
	{FlagName: "status", FieldPath: "Status", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"pending", "invoiced"}, Description: "Filter by line item status. 'pending' returns items not yet on an invoice, 'invoiced' returns items already assigned to an invoice. Omit to return both. Cannot be combined with invoiceId — when filtering by invoice ID all statuses are returned. (options: pending, invoiced)"},
	{FlagName: "invoice-id", Shorthand: "i", FieldPath: "InvoiceID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by invoice ID. When provided without subscriptionId, returns all line items for that invoice. At least one of subscriptionId or invoiceId must be provided."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 100, Description: "Maximum number of line items to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "Number of line items to skip for pagination"},
}

// initListLineItemsCmd initializes the list-line-items command.
func initListLineItemsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-line-items",
		Short:   "List Line Items",
		Long:    "List pending and invoiced line items for a subscription from the billing database. Returns exact fee amounts and estimated metered charges.",
		Example: "  paygentic invoices-v2 list-line-items",
		RunE:    runListLineItemsCmd,
		Aliases: []string{"lli"},
	}
	flagutil.RegisterFlags(cmd, listLineItemsCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListLineItemsRequest](listLineItemsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-line-items: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListLineItemsCmd executes the list-line-items command.
func runListLineItemsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listLineItemsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listLineItemsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListLineItemsRequest](cmd, listLineItemsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.InvoicesV2.ListLineItems(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
