// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9b0dc10cc70f

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateOrderResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Order created
	Order *components.Order
}

func (c CreateOrderResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrderResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrderResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateOrderResponse) GetOrder() *components.Order {
	if c == nil {
		return nil
	}
	return c.Order
}
