// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 6f3e26ada814

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateEntitlementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Entitlement created successfully
	Entitlement *components.Entitlement
}

func (c CreateEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntitlementResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEntitlementResponse) GetEntitlement() *components.Entitlement {
	if c == nil {
		return nil
	}
	return c.Entitlement
}
