// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f652223a15cd

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateBillingScheduleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// BillingSchedule created
	SchemasBillingSchedule *components.SchemasBillingSchedule
}

func (c CreateBillingScheduleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateBillingScheduleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateBillingScheduleResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateBillingScheduleResponse) GetSchemasBillingSchedule() *components.SchemasBillingSchedule {
	if c == nil {
		return nil
	}
	return c.SchemasBillingSchedule
}
