// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateLineItemRequest struct {
	// Optional idempotency key. If provided, duplicate requests with the same key return the previously created item.
	IdempotencyKey *string                                `header:"style=simple,explode=false,name=Idempotency-Key"`
	Body           components.CreateManualLineItemRequest `request:"mediaType=application/json"`
}

func (c *CreateLineItemRequest) GetIdempotencyKey() *string {
	if c == nil {
		return nil
	}
	return c.IdempotencyKey
}

func (c *CreateLineItemRequest) GetBody() components.CreateManualLineItemRequest {
	if c == nil {
		return components.CreateManualLineItemRequest{}
	}
	return c.Body
}

type CreateLineItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Idempotent retry — returns previously created item
	LineItem *components.LineItem
}

func (c CreateLineItemResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateLineItemResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateLineItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateLineItemResponse) GetLineItem() *components.LineItem {
	if c == nil {
		return nil
	}
	return c.LineItem
}
