// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 151c7e415893

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateApprovalResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Approval created
	SchemasApproval *components.SchemasApproval
}

func (c CreateApprovalResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateApprovalResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateApprovalResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateApprovalResponse) GetSchemasApproval() *components.SchemasApproval {
	if c == nil {
		return nil
	}
	return c.SchemasApproval
}
