// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9799d721e8bf

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateOrderLineItemRequest struct {
	OrderID string                                `pathParam:"style=simple,explode=false,name=orderId"`
	Body    components.CreateOrderLineItemRequest `request:"mediaType=application/json"`
}

func (c *CreateOrderLineItemRequest) GetOrderID() string {
	if c == nil {
		return ""
	}
	return c.OrderID
}

func (c *CreateOrderLineItemRequest) GetBody() components.CreateOrderLineItemRequest {
	if c == nil {
		return components.CreateOrderLineItemRequest{}
	}
	return c.Body
}

type CreateOrderLineItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Line item created
	OrderLineItem *components.OrderLineItem
}

func (c CreateOrderLineItemResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateOrderLineItemResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateOrderLineItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateOrderLineItemResponse) GetOrderLineItem() *components.OrderLineItem {
	if c == nil {
		return nil
	}
	return c.OrderLineItem
}
