// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5701b4d9afd9

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateEntitlementGrantRequest struct {
	// The unique identifier of the entitlement to grant credits to.
	EntitlementID string                        `pathParam:"style=simple,explode=false,name=entitlementId"`
	Body          components.CreateGrantRequest `request:"mediaType=application/json"`
}

func (c *CreateEntitlementGrantRequest) GetEntitlementID() string {
	if c == nil {
		return ""
	}
	return c.EntitlementID
}

func (c *CreateEntitlementGrantRequest) GetBody() components.CreateGrantRequest {
	if c == nil {
		return components.CreateGrantRequest{}
	}
	return c.Body
}

type CreateEntitlementGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Grant successfully created.
	Grant *components.Grant
}

func (c CreateEntitlementGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateEntitlementGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateEntitlementGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateEntitlementGrantResponse) GetGrant() *components.Grant {
	if c == nil {
		return nil
	}
	return c.Grant
}
