// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f0a527c23c8a

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateCustomerPaymentMethodRequestBody struct {
	// URL the customer is redirected to on success. When the page is iframed, success is reported via `postMessage` instead.
	SuccessRedirectURL *string `json:"successRedirectUrl,omitzero"`
	// URL the customer is redirected to on failure. When the page is iframed, failure is reported via `postMessage` instead.
	FailureRedirectURL *string `json:"failureRedirectUrl,omitzero"`
	// Arbitrary key/value pairs to attach to the session.
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (c CreateCustomerPaymentMethodRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerPaymentMethodRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCustomerPaymentMethodRequestBody) GetSuccessRedirectURL() *string {
	if c == nil {
		return nil
	}
	return c.SuccessRedirectURL
}

func (c *CreateCustomerPaymentMethodRequestBody) GetFailureRedirectURL() *string {
	if c == nil {
		return nil
	}
	return c.FailureRedirectURL
}

func (c *CreateCustomerPaymentMethodRequestBody) GetMetadata() map[string]any {
	if c == nil {
		return nil
	}
	return c.Metadata
}

type CreateCustomerPaymentMethodRequest struct {
	// The unique identifier of the customer.
	ID   string                                  `pathParam:"style=simple,explode=false,name=id"`
	Body *CreateCustomerPaymentMethodRequestBody `request:"mediaType=application/json"`
}

func (c CreateCustomerPaymentMethodRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerPaymentMethodRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCustomerPaymentMethodRequest) GetID() string {
	if c == nil {
		return ""
	}
	return c.ID
}

func (c *CreateCustomerPaymentMethodRequest) GetBody() *CreateCustomerPaymentMethodRequestBody {
	if c == nil {
		return nil
	}
	return c.Body
}

type CreateCustomerPaymentMethodResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Payment session created successfully
	PaymentSession *components.PaymentSession
}

func (c CreateCustomerPaymentMethodResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCustomerPaymentMethodResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCustomerPaymentMethodResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCustomerPaymentMethodResponse) GetPaymentSession() *components.PaymentSession {
	if c == nil {
		return nil
	}
	return c.PaymentSession
}
