// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type CreateUsageEventResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Usage event created successfully
	UsageEvent *components.UsageEvent
}

func (c CreateUsageEventResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateUsageEventResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateUsageEventResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateUsageEventResponse) GetUsageEvent() *components.UsageEvent {
	if c == nil {
		return nil
	}
	return c.UsageEvent
}
