// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8aa060c805f1

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"io"
)

type DownloadInvoicePdfRequest struct {
	// The invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DownloadInvoicePdfRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DownloadInvoicePdfResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The invoice document
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (d *DownloadInvoicePdfResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DownloadInvoicePdfResponse) GetResponseStream() io.ReadCloser {
	if d == nil {
		return nil
	}
	return d.ResponseStream
}
