// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5bd8d8b5155f

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type GetActiveEntitlementsRequest struct {
	// The customer ID to get active entitlements for.
	CustomerID string `queryParam:"style=form,explode=true,name=customerId"`
	// The product ID to get active entitlements for.
	ProductID *string `queryParam:"style=form,explode=true,name=productId"`
	// The subscription ID to get active entitlements for.
	SubscriptionID *string `queryParam:"style=form,explode=true,name=subscriptionId"`
}

func (g *GetActiveEntitlementsRequest) GetCustomerID() string {
	if g == nil {
		return ""
	}
	return g.CustomerID
}

func (g *GetActiveEntitlementsRequest) GetProductID() *string {
	if g == nil {
		return nil
	}
	return g.ProductID
}

func (g *GetActiveEntitlementsRequest) GetSubscriptionID() *string {
	if g == nil {
		return nil
	}
	return g.SubscriptionID
}

type GetActiveEntitlementsObject string

const (
	GetActiveEntitlementsObjectList GetActiveEntitlementsObject = "list"
)

func (e GetActiveEntitlementsObject) ToPointer() *GetActiveEntitlementsObject {
	return &e
}
func (e *GetActiveEntitlementsObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = GetActiveEntitlementsObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetActiveEntitlementsObject: %v", v)
	}
}

type GetActiveEntitlementsPagination struct {
	Offset *float64 `json:"offset,omitzero"`
	Limit  *float64 `json:"limit,omitzero"`
	Total  *float64 `json:"total,omitzero"`
}

func (g *GetActiveEntitlementsPagination) GetOffset() *float64 {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetActiveEntitlementsPagination) GetLimit() *float64 {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetActiveEntitlementsPagination) GetTotal() *float64 {
	if g == nil {
		return nil
	}
	return g.Total
}

// GetActiveEntitlementsResponseBody - List of active entitlements
type GetActiveEntitlementsResponseBody struct {
	Object     *GetActiveEntitlementsObject     `default:"list" json:"object"`
	Data       []components.ActiveEntitlement   `json:"data,omitzero"`
	Pagination *GetActiveEntitlementsPagination `json:"pagination,omitzero"`
}

func (g GetActiveEntitlementsResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActiveEntitlementsResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetActiveEntitlementsResponseBody) GetObject() *GetActiveEntitlementsObject {
	if g == nil {
		return nil
	}
	return g.Object
}

func (g *GetActiveEntitlementsResponseBody) GetData() []components.ActiveEntitlement {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetActiveEntitlementsResponseBody) GetPagination() *GetActiveEntitlementsPagination {
	if g == nil {
		return nil
	}
	return g.Pagination
}

type GetActiveEntitlementsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of active entitlements
	Object *GetActiveEntitlementsResponseBody
}

func (g GetActiveEntitlementsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetActiveEntitlementsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetActiveEntitlementsResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetActiveEntitlementsResponse) GetObject() *GetActiveEntitlementsResponseBody {
	if g == nil {
		return nil
	}
	return g.Object
}
