// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4dffea385575

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type GetEntitlementGrantRequest struct {
	// The unique identifier of the entitlement.
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlementId"`
	// The unique identifier of the grant.
	GrantID string `pathParam:"style=simple,explode=false,name=grantId"`
}

func (g *GetEntitlementGrantRequest) GetEntitlementID() string {
	if g == nil {
		return ""
	}
	return g.EntitlementID
}

func (g *GetEntitlementGrantRequest) GetGrantID() string {
	if g == nil {
		return ""
	}
	return g.GrantID
}

type GetEntitlementGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successfully retrieved the grant.
	Grant *components.Grant
}

func (g GetEntitlementGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetEntitlementGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetEntitlementGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetEntitlementGrantResponse) GetGrant() *components.Grant {
	if g == nil {
		return nil
	}
	return g.Grant
}
