// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1ebe45d9854a

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type GetExternalReferenceRequest struct {
	// The unique identifier of the external reference
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetExternalReferenceRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetExternalReferenceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// External reference
	ExternalReference *components.ExternalReference
}

func (g GetExternalReferenceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetExternalReferenceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetExternalReferenceResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetExternalReferenceResponse) GetExternalReference() *components.ExternalReference {
	if g == nil {
		return nil
	}
	return g.ExternalReference
}
