// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d4eb51f689de

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type GetFeatureRequest struct {
	// The unique identifier of the feature
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (g *GetFeatureRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

type GetFeatureResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Feature details
	Feature *components.Feature
}

func (g GetFeatureResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetFeatureResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetFeatureResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetFeatureResponse) GetFeature() *components.Feature {
	if g == nil {
		return nil
	}
	return g.Feature
}
