// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4f7626bbb5c0

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type GetProfitabilityRequest struct {
	// Merchant whose customers to summarize
	MerchantID string `queryParam:"style=form,explode=true,name=merchantId"`
	// Start of the time range (ISO 8601 format)
	From time.Time `queryParam:"style=form,explode=true,name=from"`
	// End of the time range (ISO 8601 format)
	To time.Time `queryParam:"style=form,explode=true,name=to"`
	// Number of top customers (by profit) to return individually. The rest are rolled into a single 'Other' row.
	TopN *int64 `default:"10" queryParam:"style=form,explode=true,name=topN"`
	// ISO 4217 currency code to scope the summary. Defaults to the merchant's primary currency.
	Currency *string `queryParam:"style=form,explode=true,name=currency"`
	// When true, leave customers with neither revenue nor cost in the period out of `rows`. They are dropped before ranking, so they take no top-N slot and are not folded into the 'Other' row. `emptyCustomerCount` says how many there are either way.
	ExcludeEmpty *bool `default:"false" queryParam:"style=form,explode=true,name=excludeEmpty"`
	// When true, also return in `emptyCustomers` the customers counted in `emptyCustomerCount` that `rows` does not carry, so a caller can show the complete customer list.
	IncludeEmpty *bool `default:"false" queryParam:"style=form,explode=true,name=includeEmpty"`
}

func (g GetProfitabilityRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProfitabilityRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProfitabilityRequest) GetMerchantID() string {
	if g == nil {
		return ""
	}
	return g.MerchantID
}

func (g *GetProfitabilityRequest) GetFrom() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.From
}

func (g *GetProfitabilityRequest) GetTo() time.Time {
	if g == nil {
		return time.Time{}
	}
	return g.To
}

func (g *GetProfitabilityRequest) GetTopN() *int64 {
	if g == nil {
		return nil
	}
	return g.TopN
}

func (g *GetProfitabilityRequest) GetCurrency() *string {
	if g == nil {
		return nil
	}
	return g.Currency
}

func (g *GetProfitabilityRequest) GetExcludeEmpty() *bool {
	if g == nil {
		return nil
	}
	return g.ExcludeEmpty
}

func (g *GetProfitabilityRequest) GetIncludeEmpty() *bool {
	if g == nil {
		return nil
	}
	return g.IncludeEmpty
}

type GetProfitabilityResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Profitability summary
	ProfitabilitySummaryResponse *components.ProfitabilitySummaryResponse
}

func (g GetProfitabilityResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetProfitabilityResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetProfitabilityResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetProfitabilityResponse) GetProfitabilitySummaryResponse() *components.ProfitabilitySummaryResponse {
	if g == nil {
		return nil
	}
	return g.ProfitabilitySummaryResponse
}
