// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: ef42af67d958

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type GetSourceRuleRequest struct {
	RuleID string `pathParam:"style=simple,explode=false,name=ruleId"`
}

func (g *GetSourceRuleRequest) GetRuleID() string {
	if g == nil {
		return ""
	}
	return g.RuleID
}

type GetSourceRuleResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Rule details
	SourceRule *components.SourceRule
}

func (g GetSourceRuleResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetSourceRuleResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetSourceRuleResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetSourceRuleResponse) GetSourceRule() *components.SourceRule {
	if g == nil {
		return nil
	}
	return g.SourceRule
}
