// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type IssueEntitlementResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Entitlement successfully issued.
	SchemasEntitlement *components.SchemasEntitlement
}

func (i IssueEntitlementResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IssueEntitlementResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (i *IssueEntitlementResponse) GetHTTPMeta() components.HTTPMetadata {
	if i == nil {
		return components.HTTPMetadata{}
	}
	return i.HTTPMeta
}

func (i *IssueEntitlementResponse) GetSchemasEntitlement() *components.SchemasEntitlement {
	if i == nil {
		return nil
	}
	return i.SchemasEntitlement
}
