// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type ListSourcesRequest struct {
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Filter sources by merchant ID
	MerchantID *string `queryParam:"style=form,explode=true,name=merchantId"`
	Offset     *int64  `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter sources by plan ID
	PlanID *string `queryParam:"style=form,explode=true,name=planId"`
}

func (l ListSourcesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSourcesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSourcesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListSourcesRequest) GetMerchantID() *string {
	if l == nil {
		return nil
	}
	return l.MerchantID
}

func (l *ListSourcesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListSourcesRequest) GetPlanID() *string {
	if l == nil {
		return nil
	}
	return l.PlanID
}

// ListSourcesResponseBody - List of sources
type ListSourcesResponseBody struct {
	Data []components.Source `json:"data,omitzero"`
	// Offset-based pagination response.
	Pagination *components.OffsetPagination `json:"pagination,omitzero"`
}

func (l ListSourcesResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSourcesResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSourcesResponseBody) GetData() []components.Source {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListSourcesResponseBody) GetPagination() *components.OffsetPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListSourcesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of sources
	Object *ListSourcesResponseBody
}

func (l ListSourcesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListSourcesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListSourcesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListSourcesResponse) GetObject() *ListSourcesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
