// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f133dd2ed6df

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type ListInvoiceRefundsRequest struct {
	// The invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (l *ListInvoiceRefundsRequest) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

type ListInvoiceRefundsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of refunds
	InvoiceRefundList *components.InvoiceRefundList
}

func (l ListInvoiceRefundsResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListInvoiceRefundsResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListInvoiceRefundsResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListInvoiceRefundsResponse) GetInvoiceRefundList() *components.InvoiceRefundList {
	if l == nil {
		return nil
	}
	return l.InvoiceRefundList
}
