// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type ListPricesRequest struct {
	// Filter prices by billable metric ID
	BillableMetricID *string `queryParam:"style=form,explode=true,name=billableMetricId"`
	// Number of prices to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of prices to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
}

func (l ListPricesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPricesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPricesRequest) GetBillableMetricID() *string {
	if l == nil {
		return nil
	}
	return l.BillableMetricID
}

func (l *ListPricesRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPricesRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

type ListPricesPagination struct {
	Limit  *int64 `json:"limit,omitzero"`
	Offset *int64 `json:"offset,omitzero"`
	Total  *int64 `json:"total,omitzero"`
}

func (l *ListPricesPagination) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPricesPagination) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListPricesPagination) GetTotal() *int64 {
	if l == nil {
		return nil
	}
	return l.Total
}

// ListPricesResponseBody - List of prices
type ListPricesResponseBody struct {
	Data       []components.SchemasPrice `json:"data,omitzero"`
	Pagination *ListPricesPagination     `json:"pagination,omitzero"`
}

func (l ListPricesResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPricesResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPricesResponseBody) GetData() []components.SchemasPrice {
	if l == nil {
		return nil
	}
	return l.Data
}

func (l *ListPricesResponseBody) GetPagination() *ListPricesPagination {
	if l == nil {
		return nil
	}
	return l.Pagination
}

type ListPricesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of prices
	Object *ListPricesResponseBody
}

func (l ListPricesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListPricesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListPricesResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListPricesResponse) GetObject() *ListPricesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
