// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type ListCustomersRequest struct {
	// Number of customers to return
	Limit *int64 `default:"10" queryParam:"style=form,explode=true,name=limit"`
	// Number of customers to skip
	Offset *int64 `default:"0" queryParam:"style=form,explode=true,name=offset"`
	// Filter customers by consumer name (case-insensitive substring match). Minimum 3 characters required for efficient index usage.
	Name *string `queryParam:"style=form,explode=true,name=name"`
	// Filter customers by billing email (case-insensitive substring match). Minimum 3 characters required for efficient index usage. Accepts partial values — e.g. a domain ("acme.com") or local part ("billing").
	Email *string `queryParam:"style=form,explode=true,name=email"`
	// Filter customers by exact external ID match.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
	// ID of the merchant organization to filter customers by
	OrganizationID string `queryParam:"style=form,explode=true,name=organizationId"`
}

func (l ListCustomersRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCustomersRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCustomersRequest) GetLimit() *int64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCustomersRequest) GetOffset() *int64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListCustomersRequest) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *ListCustomersRequest) GetEmail() *string {
	if l == nil {
		return nil
	}
	return l.Email
}

func (l *ListCustomersRequest) GetExternalID() *string {
	if l == nil {
		return nil
	}
	return l.ExternalID
}

func (l *ListCustomersRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

type ListCustomersObject string

const (
	ListCustomersObjectList ListCustomersObject = "list"
)

func (e ListCustomersObject) ToPointer() *ListCustomersObject {
	return &e
}
func (e *ListCustomersObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "list":
		*e = ListCustomersObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListCustomersObject: %v", v)
	}
}

// ListCustomersResponseBody - List of customers retrieved successfully
type ListCustomersResponseBody struct {
	Object ListCustomersObject   `json:"object"`
	Data   []components.Customer `json:"data"`
	// Offset-based pagination response.
	Pagination components.OffsetPagination `json:"pagination"`
}

func (l *ListCustomersResponseBody) GetObject() ListCustomersObject {
	if l == nil {
		return ListCustomersObject("")
	}
	return l.Object
}

func (l *ListCustomersResponseBody) GetData() []components.Customer {
	if l == nil {
		return []components.Customer{}
	}
	return l.Data
}

func (l *ListCustomersResponseBody) GetPagination() components.OffsetPagination {
	if l == nil {
		return components.OffsetPagination{}
	}
	return l.Pagination
}

type ListCustomersResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// List of customers retrieved successfully
	Object *ListCustomersResponseBody
}

func (l ListCustomersResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListCustomersResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *ListCustomersResponse) GetHTTPMeta() components.HTTPMetadata {
	if l == nil {
		return components.HTTPMetadata{}
	}
	return l.HTTPMeta
}

func (l *ListCustomersResponse) GetObject() *ListCustomersResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}
