// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7c241024d037

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type ReconcileSubscriptionFeaturesRequestBody struct {
	// Preview the outcome without creating any entitlement, grant, or line item.
	DryRun *bool `default:"false" json:"dryRun"`
}

func (r ReconcileSubscriptionFeaturesRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReconcileSubscriptionFeaturesRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReconcileSubscriptionFeaturesRequestBody) GetDryRun() *bool {
	if r == nil {
		return nil
	}
	return r.DryRun
}

type ReconcileSubscriptionFeaturesRequest struct {
	// The subscription ID
	ID   string                                    `pathParam:"style=simple,explode=false,name=id"`
	Body *ReconcileSubscriptionFeaturesRequestBody `request:"mediaType=application/json"`
}

func (r ReconcileSubscriptionFeaturesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReconcileSubscriptionFeaturesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReconcileSubscriptionFeaturesRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *ReconcileSubscriptionFeaturesRequest) GetBody() *ReconcileSubscriptionFeaturesRequestBody {
	if r == nil {
		return nil
	}
	return r.Body
}

type ReconcileSubscriptionFeaturesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The reconciliation did not create a full set of resources: a dry-run preview (nothing is created), a run in which one or more features could not be fully provisioned (billing is withheld until they succeed), or a run whose entitlements provisioned but whose line-item synchronization failed. Safe to retry — re-invoking this operation will not duplicate any entitlements or grants already provisioned.
	SubscriptionReconciliation *components.SubscriptionReconciliation
}

func (r ReconcileSubscriptionFeaturesResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReconcileSubscriptionFeaturesResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *ReconcileSubscriptionFeaturesResponse) GetHTTPMeta() components.HTTPMetadata {
	if r == nil {
		return components.HTTPMetadata{}
	}
	return r.HTTPMeta
}

func (r *ReconcileSubscriptionFeaturesResponse) GetSubscriptionReconciliation() *components.SubscriptionReconciliation {
	if r == nil {
		return nil
	}
	return r.SubscriptionReconciliation
}
