// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type TerminateSubscriptionRequestBody struct {
	// Cancellation explanation text. Sample values: 'Customer requested cancellation', 'Payment failure', 'Service migration', 'Contract expiration'
	Reason string `json:"reason"`
}

func (t *TerminateSubscriptionRequestBody) GetReason() string {
	if t == nil {
		return ""
	}
	return t.Reason
}

type TerminateSubscriptionRequest struct {
	// The subscription ID
	ID   string                           `pathParam:"style=simple,explode=false,name=id"`
	Body TerminateSubscriptionRequestBody `request:"mediaType=application/json"`
}

func (t *TerminateSubscriptionRequest) GetID() string {
	if t == nil {
		return ""
	}
	return t.ID
}

func (t *TerminateSubscriptionRequest) GetBody() TerminateSubscriptionRequestBody {
	if t == nil {
		return TerminateSubscriptionRequestBody{}
	}
	return t.Body
}

type TerminateSubscriptionResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Subscription terminated successfully
	Subscription *components.Subscription
}

func (t TerminateSubscriptionResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TerminateSubscriptionResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (t *TerminateSubscriptionResponse) GetHTTPMeta() components.HTTPMetadata {
	if t == nil {
		return components.HTTPMetadata{}
	}
	return t.HTTPMeta
}

func (t *TerminateSubscriptionResponse) GetSubscription() *components.Subscription {
	if t == nil {
		return nil
	}
	return t.Subscription
}
