// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 252e7a2196b2

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type UpdateItemRequestBody struct {
	Name     *string        `json:"name,omitzero"`
	Metadata map[string]any `json:"metadata,omitzero"`
}

func (u UpdateItemRequestBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateItemRequestBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateItemRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateItemRequestBody) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

type UpdateItemRequest struct {
	// The unique identifier of the item
	ID   string                `pathParam:"style=simple,explode=false,name=id"`
	Body UpdateItemRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateItemRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateItemRequest) GetBody() UpdateItemRequestBody {
	if u == nil {
		return UpdateItemRequestBody{}
	}
	return u.Body
}

type UpdateItemResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Item updated
	Item *components.Item
}

func (u UpdateItemResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *UpdateItemResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *UpdateItemResponse) GetHTTPMeta() components.HTTPMetadata {
	if u == nil {
		return components.HTTPMetadata{}
	}
	return u.HTTPMeta
}

func (u *UpdateItemResponse) GetItem() *components.Item {
	if u == nil {
		return nil
	}
	return u.Item
}
