// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a63002b0f96f

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type VoidInvoiceRefundRequestBody struct {
	// Optional reason for voiding the refund (recorded on the credit note)
	Reason *string `json:"reason,omitzero"`
}

func (v *VoidInvoiceRefundRequestBody) GetReason() *string {
	if v == nil {
		return nil
	}
	return v.Reason
}

type VoidInvoiceRefundRequest struct {
	// The invoice ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// The refund (credit note) ID
	RefundID string                        `pathParam:"style=simple,explode=false,name=refundId"`
	Body     *VoidInvoiceRefundRequestBody `request:"mediaType=application/json"`
}

func (v VoidInvoiceRefundRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VoidInvoiceRefundRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VoidInvoiceRefundRequest) GetID() string {
	if v == nil {
		return ""
	}
	return v.ID
}

func (v *VoidInvoiceRefundRequest) GetRefundID() string {
	if v == nil {
		return ""
	}
	return v.RefundID
}

func (v *VoidInvoiceRefundRequest) GetBody() *VoidInvoiceRefundRequestBody {
	if v == nil {
		return nil
	}
	return v.Body
}

type VoidInvoiceRefundResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Refund voided
	InvoiceRefund *components.InvoiceRefund
}

func (v VoidInvoiceRefundResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VoidInvoiceRefundResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VoidInvoiceRefundResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VoidInvoiceRefundResponse) GetInvoiceRefund() *components.InvoiceRefund {
	if v == nil {
		return nil
	}
	return v.InvoiceRefund
}
