// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 7ec1e6fcc93f

package operations

import (
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

type VoidEntitlementGrantRequest struct {
	// The unique identifier of the entitlement.
	EntitlementID string `pathParam:"style=simple,explode=false,name=entitlementId"`
	// The unique identifier of the grant to void.
	GrantID string `pathParam:"style=simple,explode=false,name=grantId"`
}

func (v *VoidEntitlementGrantRequest) GetEntitlementID() string {
	if v == nil {
		return ""
	}
	return v.EntitlementID
}

func (v *VoidEntitlementGrantRequest) GetGrantID() string {
	if v == nil {
		return ""
	}
	return v.GrantID
}

type VoidEntitlementGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Grant successfully voided (or already voided).
	Grant *components.Grant
}

func (v VoidEntitlementGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *VoidEntitlementGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (v *VoidEntitlementGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if v == nil {
		return components.HTTPMetadata{}
	}
	return v.HTTPMeta
}

func (v *VoidEntitlementGrantResponse) GetGrant() *components.Grant {
	if v == nil {
		return nil
	}
	return v.Grant
}
