// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4e5f6c928f11

package sdkerrors

import (
	"encoding/json"
	"github.com/paygentic/cli/internal/sdk/models/components"
)

type Error struct {
	// Coarse HTTP error category (e.g. 'bad_request', 'forbidden'). Maps to the HTTP status code.
	Error_ *string `json:"error,omitzero"`
	// Human-readable error message. Clients must not parse this field programmatically.
	Message string `json:"message"`
	// Optional semantic business error code for machine-readable discrimination (e.g. 'TAX_NOT_ENABLED'). UPPER_SNAKE_CASE. Clients should check this field, not message.
	Code *components.Code `json:"code,omitzero"`
	// Additional error details
	Details  map[string]any          `json:"details,omitzero"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &Error{}

func (e *Error) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
