// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"github.com/paygentic/cli/internal/sdk/models/components"
)

type ValidationError struct {
	// Error type indicating validation failure
	Error_ *components.ErrorEnum `default:"validation_error" json:"error"`
	// Human-readable error message
	Message string `json:"message"`
	// Array of field-specific validation errors
	Errors   []components.Error      `json:"errors"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &ValidationError{}

func (e *ValidationError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
