// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package testclocks

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitTestClocksRoot(parent *cobra.Command) error {
	var TestClocksCmd = &cobra.Command{
		Use:   "test-clocks",
		Short: "Test clocks provide programmable time control to simulate subscription and billing scenarios during testing",
		Long:  "Test clocks provide programmable time control to simulate subscription and billing scenarios during testing.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
		Aliases: []string{"tc"},
	}

	if err := initListCmd(TestClocksCmd); err != nil {
		return err
	}

	if err := initCreateCmd(TestClocksCmd); err != nil {
		return err
	}

	if err := initGetCmd(TestClocksCmd); err != nil {
		return err
	}

	if err := initAdvanceCmd(TestClocksCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(TestClocksCmd); err != nil {
		return err
	}

	parent.AddCommand(TestClocksCmd)
	return nil
}
