// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 0832d1354841

package externalreferences

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listExternalReferencesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "merchant-id", Shorthand: "m", FieldPath: "MerchantID", Kind: flagutil.FlagKindString, Optional: true, Description: "Restrict results to a specific merchant. All active filters AND together."},
	{FlagName: "entity-type", FieldPath: "EntityType", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"item"}, Description: "Filter by the Paygentic entity type the reference points at (e.g. `item`). All active filters AND together. (options: item)"},
	{FlagName: "entity-id", FieldPath: "EntityID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by the Paygentic entity id (e.g. `itm_xxx`). This is the inverse of the `GET /v0/items?provider=&externalId=` resolution endpoint — look up references from the Paygentic side. All active filters AND together."},
	{FlagName: "provider", Shorthand: "p", FieldPath: "Provider", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by provider (e.g. `salesforce`, `netsuite`). All active filters AND together."},
	{FlagName: "external-id", FieldPath: "ExternalID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by the external system's record id. Pair with `provider` to look up all Paygentic entities that carry a given external reference. All active filters AND together."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 50, Description: "integer value"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "integer value"},
}

// initListExternalReferencesCmd initializes the list-external-references command.
func initListExternalReferencesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List",
		Long:    "List",
		Example: "  paygentic external-references list",
		RunE:    runListExternalReferencesCmd,
	}
	flagutil.RegisterFlags(cmd, listExternalReferencesCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListExternalReferencesRequest](listExternalReferencesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-external-references: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListExternalReferencesCmd executes the list-external-references command.
func runListExternalReferencesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listExternalReferencesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listExternalReferencesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListExternalReferencesRequest](cmd, listExternalReferencesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ExternalReferences.ListExternalReferences(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
