// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: cdd227d712da

package externalreferences

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateExternalReferenceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the external reference [required]"},
	{FlagName: "external-label", Shorthand: "e", FieldPath: "Body.ExternalLabel", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"externalLabel,omitempty"`, Description: "string value"},
	{FlagName: "metadata", Shorthand: "m", FieldPath: "Body.Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "value"},
	{FlagName: "is-primary", FieldPath: "Body.IsPrimary", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "is-default", FieldPath: "Body.IsDefault", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
}

// initUpdateExternalReferenceCmd initializes the update-external-reference command.
func initUpdateExternalReferenceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update",
		Long:    "Update",
		Example: "  paygentic external-references update --id <id>",
		RunE:    runUpdateExternalReferenceCmd,
	}
	flagutil.RegisterFlags(cmd, updateExternalReferenceCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateExternalReferenceRequest](updateExternalReferenceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-external-reference: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateExternalReferenceCmd executes the update-external-reference command.
func runUpdateExternalReferenceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateExternalReferenceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateExternalReferenceCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UpdateExternalReferenceRequest](cmd, updateExternalReferenceCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.ExternalReferences.UpdateExternalReference(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
