// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sourcesevents

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var rejectCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "event-id", Shorthand: "e", FieldPath: "EventID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initRejectCmd initializes the reject command.
func initRejectCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "reject",
		Short:   "Reject",
		Long:    "Reject a pending source event",
		Example: "  paygentic sources-events reject --id <id> --event-id <id>",
		RunE:    runRejectCmd,
	}
	flagutil.RegisterFlags(cmd, rejectCmdMeta)
	if err := flagutil.ValidateMeta[operations.RejectSourceEventRequest](rejectCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for reject: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runRejectCmd executes the reject command.
func runRejectCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, rejectCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, rejectCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.RejectSourceEventRequest](cmd, rejectCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Sources.Events.Reject(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
