// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sourcesevents

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSourcesEventsRoot(parent *cobra.Command) error {
	var SourcesEventsCmd = &cobra.Command{
		Use:   "events",
		Short: "Operations for sources-events",
		Long:  "Operations for sources-events",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(SourcesEventsCmd); err != nil {
		return err
	}

	if err := initApproveCmd(SourcesEventsCmd); err != nil {
		return err
	}

	if err := initRejectCmd(SourcesEventsCmd); err != nil {
		return err
	}

	if err := initBulkApproveCmd(SourcesEventsCmd); err != nil {
		return err
	}

	if err := initBulkRejectCmd(SourcesEventsCmd); err != nil {
		return err
	}

	parent.AddCommand(SourcesEventsCmd)
	return nil
}
