// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d029caa89d21

package subscriptions

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var generatePortalLinkCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The subscription ID [required]"},
	{FlagName: "expires-in", Shorthand: "e", FieldPath: "Body.ExpiresIn", Kind: flagutil.FlagKindString, Optional: true, Description: "Token lifetime as an ISO 8601 duration. Defaults to PT10M (10 minutes). Maximum is P7D (7 days). Examples: PT10M, PT1H, P1D, P7D."},
}

// initGeneratePortalLinkCmd initializes the generate-portal-link command.
func initGeneratePortalLinkCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "generate-portal-link",
		Short:   "Generate Portal Link",
		Long:    "Generates a secure, time-limited URL that allows customers to access their subscription data without authentication.",
		Example: "  paygentic subscriptions generate-portal-link --id <id>",
		RunE:    runGeneratePortalLinkCmd,
		Aliases: []string{"gpl"},
	}
	flagutil.RegisterFlags(cmd, generatePortalLinkCmdMeta)
	if err := flagutil.ValidateMeta[operations.GeneratePortalLinkRequest](generatePortalLinkCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for generate-portal-link: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runGeneratePortalLinkCmd executes the generate-portal-link command.
func runGeneratePortalLinkCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, generatePortalLinkCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, generatePortalLinkCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GeneratePortalLinkRequest](cmd, generatePortalLinkCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Subscriptions.GeneratePortalLink(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
