// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 45abc62f9dc4

package subscriptions

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getSubscriptionIntervalsCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The subscription ID [required]"},
}

// initGetSubscriptionIntervalsCmd initializes the get-subscription-intervals command.
func initGetSubscriptionIntervalsCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-subscription-intervals",
		Short:   "Get Price Intervals",
		Long:    "Returns all the price intervals of the subscription, ordered by start date. This includes intervals that ended and intervals that start in the future. If there are none, returns an empty array.",
		Example: "  paygentic subscriptions get-subscription-intervals --id <id>",
		RunE:    runGetSubscriptionIntervalsCmd,
		Aliases: []string{"gsi"},
	}
	flagutil.RegisterFlags(cmd, getSubscriptionIntervalsCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetSubscriptionIntervalsRequest](getSubscriptionIntervalsCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-subscription-intervals: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetSubscriptionIntervalsCmd executes the get-subscription-intervals command.
func runGetSubscriptionIntervalsCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getSubscriptionIntervalsCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getSubscriptionIntervalsCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetSubscriptionIntervalsRequest](cmd, getSubscriptionIntervalsCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Subscriptions.GetSubscriptionIntervals(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
