// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4ed31abbf1d5

package subscriptions

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listIntervalChangesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindString, Optional: true, HasDefault: true, DefaultStr: "10", Description: "Number of interval changes to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindString, Optional: true, HasDefault: true, DefaultStr: "0", Description: "Number of interval changes to skip"},
	{FlagName: "from", Shorthand: "f", FieldPath: "From", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "Only return changes recorded at or after this time"},
	{FlagName: "to", Shorthand: "t", FieldPath: "To", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "Only return changes recorded before this time"},
	{FlagName: "change-reason", Shorthand: "c", FieldPath: "ChangeReason", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"commercial", "correction", "migration", "unspecified"}, Description: "Only return changes with this reason. (options: commercial, correction, migration, unspecified)"},
}

// initListIntervalChangesCmd initializes the list-interval-changes command.
func initListIntervalChangesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-interval-changes",
		Short:   "List Merchant Interval Changes",
		Long:    "Lists the interval changes of all your subscriptions, oldest first. `from` is included and `to` is excluded.",
		Example: "  paygentic subscriptions list-interval-changes",
		RunE:    runListIntervalChangesCmd,
		Aliases: []string{"lic"},
	}
	flagutil.RegisterFlags(cmd, listIntervalChangesCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListIntervalChangesRequest](listIntervalChangesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-interval-changes: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListIntervalChangesCmd executes the list-interval-changes command.
func runListIntervalChangesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listIntervalChangesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listIntervalChangesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListIntervalChangesRequest](cmd, listIntervalChangesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Subscriptions.ListIntervalChanges(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
