// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 5d03d7f93e0b

package merchantintegrations

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getMerchantIntegrationCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the merchant integration [required]"},
}

// initGetMerchantIntegrationCmd initializes the get-merchant-integration command.
func initGetMerchantIntegrationCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get",
		Long:    "Get",
		Example: "  paygentic merchant-integrations get --id <id>",
		RunE:    runGetMerchantIntegrationCmd,
	}
	flagutil.RegisterFlags(cmd, getMerchantIntegrationCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetMerchantIntegrationRequest](getMerchantIntegrationCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-merchant-integration: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetMerchantIntegrationCmd executes the get-merchant-integration command.
func runGetMerchantIntegrationCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getMerchantIntegrationCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getMerchantIntegrationCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetMerchantIntegrationRequest](cmd, getMerchantIntegrationCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.MerchantIntegrations.GetMerchantIntegration(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
