// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 4d82672ac5eb

package entitlements

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listCmdMeta = []flagutil.FlagMeta{
	{FlagName: "customer-id", Shorthand: "c", FieldPath: "CustomerID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the customer to retrieve entitlements for. [required]"},
	{FlagName: "feature-key", Shorthand: "f", FieldPath: "FeatureKey", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter results to a specific feature by its key. When specified, `productId` is also required. Use this to check access to a single feature."},
	{FlagName: "product-id", Shorthand: "p", FieldPath: "ProductID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter results to entitlements for a specific product. Required when `featureKey` is specified since feature keys are scoped to products."},
	{FlagName: "subscription-id", Shorthand: "s", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter results to entitlements for a specific subscription."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "Maximum number of entitlements to return per page. Use with `offset` for pagination."},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "Number of entitlements to skip. Use with `limit` for pagination through large result sets."},
	{FlagName: "at", Shorthand: "a", FieldPath: "At", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "Evaluate balance and access at this point in time (RFC 3339 datetime with any UTC offset, e.g. 2024-01-15T10:30:00Z or 2024-01-15T15:30:00+05:30). Defaults to current time."},
}

// initListCmd initializes the list command.
func initListCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List Entitlements",
		Long:    "Retrieve all entitlements for a customer, optionally filtered by feature or product.",
		Example: "  paygentic entitlements list --customer-id cus_q3r4s5t6u7v8w9x0",
		RunE:    runListCmd,
	}
	flagutil.RegisterFlags(cmd, listCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListEntitlementsRequest](listCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListCmd executes the list command.
func runListCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListEntitlementsRequest](cmd, listCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Entitlements.List(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
