// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 68845f589717

package usageevents

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var batchCreateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "events", Shorthand: "e", FieldPath: "Events", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"events"`, Description: "[required]"},
}

// initBatchCreateCmd initializes the batch-create command.
func initBatchCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "batch-create",
		Short:   "Batch Create",
		Long:    "Creates multiple usage events in a single request. The idempotencyKey for each event is used to ensure the event is processed only once by downstream consumers, even if the same event is submitted multiple times. Duplicate submissions will be accepted and return the same response.",
		Example: "  paygentic usage-events batch-create --events '[]'",
		RunE:    runBatchCreateCmd,
		Aliases: []string{"bc"},
	}
	flagutil.RegisterFlags(cmd, batchCreateCmdMeta)
	if err := flagutil.ValidateMeta[operations.BatchCreateUsageEventsRequest](batchCreateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for batch-create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runBatchCreateCmd executes the batch-create command.
func runBatchCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, batchCreateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, batchCreateCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.BatchCreateUsageEventsRequest](cmd, batchCreateCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.UsageEvents.BatchCreate(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
