// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: fd0215578617

package usageevents

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "customer-id", Shorthand: "c", FieldPath: "CustomerID", Kind: flagutil.FlagKindString, Required: true, Description: "Customer identifier that generated this consumption event. Sample values: 'cus_abc123xyz', 'cus_789def456' [required]"},
	{FlagName: "entitlement-id", Shorthand: "e", FieldPath: "EntitlementID", Kind: flagutil.FlagKindString, Optional: true, Description: "Commitment identifier for this consumption event. Sample values: 'com_abc123xyz', 'com_789def456'"},
	{FlagName: "idempotency-key", Shorthand: "i", FieldPath: "IdempotencyKey", Kind: flagutil.FlagKindString, Required: true, Description: "Unique deduplication key preventing duplicate event processing. Sample values: 'usg_2024_01_15_abc123', 'event_wallet_xyz789', 'consumption_ref_456def' [required]"},
	{FlagName: "merchant-id", FieldPath: "MerchantID", Kind: flagutil.FlagKindString, Required: true, Description: "Merchant organization identifier owning this consumption event. Sample values: 'org_abc123xyz', 'org_789def456' [required]"},
	{FlagName: "metadata", FieldPath: "Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "Custom key-value attributes providing context about the consumption event. Sample values: {\"model_name\": \"claude-3-opus\", \"input_tokens\": \"1500\", \"output_tokens\": \"800\"} or {\"storage_tier\": \"premium\", \"data_center\": \"eu-west-1\", \"encryption\": \"enabled\"} or {\"image_resolution\": \"1024x1024\", \"generation_model\": \"stable-diffusion-xl\"}"},
	{FlagName: "properties", Shorthand: "p", FieldPath: "Properties", Kind: flagutil.FlagKindJSON, Required: true, Annotations: `json:"properties"`, Description: "[required]"},
	{FlagName: "timestamp", Shorthand: "t", FieldPath: "Timestamp", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Actual occurrence timestamp for the consumption event in ISO 8601 format. Sample values: '2024-01-15T10:30:00Z', '2024-02-01T14:45:30Z'. Represents when the event occurred, not when Paygentic received it. [required]"},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create",
		Long:    "Creates a usage event. The idempotencyKey is used to ensure the event is processed only once by downstream consumers, even if the same event is submitted multiple times. Duplicate submissions will be accepted and return the same response.",
		Example: "  paygentic usage-events create --customer-id <id> --idempotency-key <value> --merchant-id <id> --properties '[]' --timestamp 2026-05-14T00:54:35.100Z",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateUsageEventRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateUsageEventRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.UsageEvents.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
