// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 1fb639592beb

package approvals

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createApprovalCmdMeta = []flagutil.FlagMeta{
	{FlagName: "merchant-id", Shorthand: "m", FieldPath: "MerchantID", Kind: flagutil.FlagKindString, Required: true, Description: "The merchant that owns the resource being approved. [required]"},
	{FlagName: "resource-type", FieldPath: "ResourceType", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"order", "invoice"}, Description: "options: order, invoice [required]"},
	{FlagName: "resource-id", FieldPath: "ResourceID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "data-snapshot-hash", FieldPath: "DataSnapshotHash", Kind: flagutil.FlagKindString, Required: true, Description: "A precomputed hash of the resource state being approved. The resource-owning domain builds this snapshot; approvals stays decoupled from any specific resource shape. [required]"},
	{FlagName: "kind", Shorthand: "k", FieldPath: "Kind", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"data_review", "financial_review", "push"}, Description: "Defaults to data_review. (options: data_review, financial_review, push)"},
	{FlagName: "note", Shorthand: "n", FieldPath: "Note", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"note,omitempty"`, Description: "string value"},
	{FlagName: "actor-id", Shorthand: "a", FieldPath: "ActorID", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional. The real user id to record as the requester. Used when the request is made via a platform-level key on behalf of a human user (e.g. from the platform Next.js frontend). When supplied and the authenticated principal is 'platform', this value overrides the derived principal as the requester. Ignored when the caller is a non-platform API key."},
}

// initCreateApprovalCmd initializes the create-approval command.
func initCreateApprovalCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Submit a resource for approval",
		Long:    "Submit a resource for approval",
		Example: "  paygentic approvals create --merchant-id <id> --resource-type invoice --resource-id <id> --data-snapshot-hash <value>",
		RunE:    runCreateApprovalCmd,
	}
	flagutil.RegisterFlags(cmd, createApprovalCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateApprovalRequest](createApprovalCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-approval: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateApprovalCmd executes the create-approval command.
func runCreateApprovalCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createApprovalCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createApprovalCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateApprovalRequest](cmd, createApprovalCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Approvals.CreateApproval(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
