// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 610ad9cc21d5

package items

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var deleteItemCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the item [required]"},
}

// initDeleteItemCmd initializes the delete-item command.
func initDeleteItemCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete",
		Short:   "Delete",
		Long:    "Delete",
		Example: "  paygentic items delete --id <id>",
		RunE:    runDeleteItemCmd,
	}
	flagutil.RegisterFlags(cmd, deleteItemCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteItemRequest](deleteItemCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-item: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteItemCmd executes the delete-item command.
func runDeleteItemCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteItemCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteItemCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteItemRequest](cmd, deleteItemCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Items.DeleteItem(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
