// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package products

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the product [required]"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindString, Optional: true, Description: "Revised product summary shown to customers. Sample values: 'Language model API access', 'Data processing and analytics service', 'AI-powered content creation platform'"},
	{FlagName: "name", Shorthand: "n", FieldPath: "Body.Name", Kind: flagutil.FlagKindString, Optional: true, Description: "Updated product title visible to customers. Sample values: 'LLM API Service', 'Data Platform', 'AI Content Generator'"},
}

// initUpdateCmd initializes the update command.
func initUpdateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update",
		Long:    "Update",
		Example: "  paygentic products update --id <id>",
		RunE:    runUpdateCmd,
	}
	flagutil.RegisterFlags(cmd, updateCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateProductRequest](updateCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateCmd executes the update command.
func runUpdateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UpdateProductRequest](cmd, updateCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Products.Update(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
