// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package payments

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitPaymentsRoot(parent *cobra.Command) error {
	var PaymentsCmd = &cobra.Command{
		Use:   "payments",
		Short: "Create and manage one-off payments",
		Long:  "Create and manage one-off payments. A payment represents a single charge that a merchant wants to collect from a customer.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(PaymentsCmd); err != nil {
		return err
	}

	if err := initCreateCmd(PaymentsCmd); err != nil {
		return err
	}

	if err := initGetCmd(PaymentsCmd); err != nil {
		return err
	}

	parent.AddCommand(PaymentsCmd)
	return nil
}
