// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package fees

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getPriceCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the fee. [required]"},
	{FlagName: "subscription-id", Shorthand: "s", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the subscription. [required]"},
}

// initGetPriceCmd initializes the get-price command.
func initGetPriceCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-price",
		Short:   "Get Fee Price",
		Long:    "Get the price for a fee in the context of a subscription. This returns the price configured for the fee in the subscription's plan, including the tax rate.",
		Example: "  paygentic fees get-price --id <id> --subscription-id <id>",
		RunE:    runGetPriceCmd,
		Aliases: []string{"gp"},
	}
	flagutil.RegisterFlags(cmd, getPriceCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetFeePriceRequest](getPriceCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-price: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetPriceCmd executes the get-price command.
func runGetPriceCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getPriceCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getPriceCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetFeePriceRequest](cmd, getPriceCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Fees.GetPrice(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
