// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 336130c5f141

package plans

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getPlanVersionCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "version-number", Shorthand: "v", FieldPath: "VersionNumber", Kind: flagutil.FlagKindInt64, Required: true, Description: "The version number within the plan (1-based). [required]"},
}

// initGetPlanVersionCmd initializes the get-plan-version command.
func initGetPlanVersionCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-plan-version",
		Short:   "Get a version",
		Long:    "Get a single plan version, including its price slots. Only accounts that can manage this plan may read its versions; versions can expose in-progress pricing, so read-only access is not sufficient.",
		Example: "  paygentic plans get-plan-version --id <id> --version-number 541574",
		RunE:    runGetPlanVersionCmd,
		Aliases: []string{"gpv"},
	}
	flagutil.RegisterFlags(cmd, getPlanVersionCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetPlanVersionRequest](getPlanVersionCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-plan-version: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetPlanVersionCmd executes the get-plan-version command.
func runGetPlanVersionCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getPlanVersionCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getPlanVersionCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetPlanVersionRequest](cmd, getPlanVersionCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Plans.GetPlanVersion(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
