// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 24c2951c033c

package plans

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listAvailableCmdMeta = []flagutil.FlagMeta{
	{FlagName: "customer-id", Shorthand: "c", FieldPath: "CustomerID", Kind: flagutil.FlagKindString, Required: true, Description: "The customer to check subscriptions for. The merchant is derived from the customer record. [required]"},
	{FlagName: "product-id", Shorthand: "p", FieldPath: "ProductID", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional filter by product ID"},
	{FlagName: "search", Shorthand: "s", FieldPath: "Search", Kind: flagutil.FlagKindString, Optional: true, Description: "Optional search text to filter plan names (case-insensitive)"},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "Number of plans to return"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "Number of plans to skip"},
}

// initListAvailableCmd initializes the list-available command.
func initListAvailableCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-available",
		Short:   "List Available Plans",
		Long:    "Retrieves all plans for a merchant that the customer does not have an active or pending subscription for. When a customer has a subscription for any plan within a product, all plans from that product are excluded.",
		Example: "  paygentic plans list-available --customer-id <id>",
		RunE:    runListAvailableCmd,
		Aliases: []string{"la"},
	}
	flagutil.RegisterFlags(cmd, listAvailableCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListAvailablePlansRequest](listAvailableCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-available: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListAvailableCmd executes the list-available command.
func runListAvailableCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listAvailableCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listAvailableCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListAvailablePlansRequest](cmd, listAvailableCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Plans.ListAvailable(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
