// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2255255c87fc

package sources

import (
	"github.com/paygentic/cli/internal/cli/sources/rules"
	"github.com/paygentic/cli/internal/cli/sources/sourcesevents"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitSourcesRoot(parent *cobra.Command) error {
	var SourcesCmd = &cobra.Command{
		Use:   "sources",
		Short: "A `Source` is an external data provider capable of automatically creating usage events",
		Long:  "A `Source` is an external data provider capable of automatically creating usage events. Configuration occurs at the plan level, enabling data retrieval from third-party platforms such as Stripe to produce billable events.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := sourcesevents.InitSourcesEventsRoot(SourcesCmd); err != nil {
		return err
	}
	if err := rules.InitRulesRoot(SourcesCmd); err != nil {
		return err
	}

	if err := initCreateCmd(SourcesCmd); err != nil {
		return err
	}

	if err := initListCmd(SourcesCmd); err != nil {
		return err
	}

	if err := initGetCmd(SourcesCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(SourcesCmd); err != nil {
		return err
	}

	parent.AddCommand(SourcesCmd)
	return nil
}
