// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 15554b630e72

package entitlementsv0

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listActiveCmdMeta = []flagutil.FlagMeta{
	{FlagName: "customer-id", Shorthand: "c", FieldPath: "CustomerID", Kind: flagutil.FlagKindString, Required: true, Description: "The customer ID to get active entitlements for. [required]"},
	{FlagName: "product-id", Shorthand: "p", FieldPath: "ProductID", Kind: flagutil.FlagKindString, Optional: true, Description: "The product ID to get active entitlements for."},
	{FlagName: "subscription-id", Shorthand: "s", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "The subscription ID to get active entitlements for."},
}

// initListActiveCmd initializes the list-active command.
func initListActiveCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list-active",
		Short:   "List by Customer",
		Long:    "List by Customer",
		Example: "  paygentic entitlements-v0 list-active --customer-id <id>",
		RunE:    runListActiveCmd,
		Aliases: []string{"la"},
	}
	flagutil.RegisterFlags(cmd, listActiveCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetActiveEntitlementsRequest](listActiveCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-active: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListActiveCmd executes the list-active command.
func runListActiveCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listActiveCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listActiveCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetActiveEntitlementsRequest](cmd, listActiveCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.EntitlementsV0.ListActive(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
