// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 88e48cddb807

package costs

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getCostReportCmdMeta = []flagutil.FlagMeta{
	{FlagName: "merchant-id", Shorthand: "m", FieldPath: "MerchantID", Kind: flagutil.FlagKindString, Optional: true, Description: "The merchant organization ID. If omitted, defaults to the merchant associated with the authenticated API key."},
	{FlagName: "from", FieldPath: "From", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Start of the query window (ISO 8601). [required]"},
	{FlagName: "to", FieldPath: "To", Kind: flagutil.FlagKindDateTime, Required: true, Description: "End of the query window (ISO 8601). [required]"},
	{FlagName: "group-by", Shorthand: "g", FieldPath: "GroupBy", Kind: flagutil.FlagKindString, Required: true, Description: "Dimension to group results by. Valid values: 'cost' (group by cost ID), 'customer' (group by customer ID), or any dimension key from a filtered cost's groupBy schema for dynamic dimension grouping. Dynamic dimension values require exactly one costId filter. [required]"},
	{FlagName: "cost-id", FieldPath: "CostID", Kind: flagutil.FlagKindStringArray, Optional: true, Description: "Filter to specific cost(s). Enables dynamic dimension grouping."},
	{FlagName: "subject", FieldPath: "Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter to a specific subject (customer/event subject ID)."},
	{FlagName: "filter-group-by", FieldPath: "FilterGroupBy", Kind: flagutil.FlagKindString, Optional: true, Description: "JSON-encoded dimension filters (e.g. {\"region\":\"us-east-1\"}). Max 4KB, max 5 keys."},
	{FlagName: "top-n", FieldPath: "TopN", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 9, Description: "Number of top groups to return. An 'Other' bucket aggregates remaining groups."},
	{FlagName: "compare-prior-period", FieldPath: "ComparePriorPeriod", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When true, include prior-period comparison data in each group."},
	{FlagName: "window-size", Shorthand: "w", FieldPath: "WindowSize", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"HOUR", "DAY", "MONTH"}, Description: "Time window granularity for the time-series breakdown. (options: HOUR, DAY, MONTH)"},
	{FlagName: "sort", FieldPath: "Sort", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "totalCost", EnumValues: []string{"totalCost", "totalQuantity"}, Description: "Field to sort groups by. (options: totalCost, totalQuantity)"},
	{FlagName: "sort-dir", FieldPath: "SortDir", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "desc", EnumValues: []string{"asc", "desc"}, Description: "Sort direction. (options: asc, desc)"},
	{FlagName: "offset", FieldPath: "Offset", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, Description: "Number of groups to skip for pagination."},
	{FlagName: "limit", Shorthand: "l", FieldPath: "Limit", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 25, Description: "Maximum number of groups to return."},
	{FlagName: "currency", FieldPath: "Currency", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter costs to a single ISO 4217 currency code (e.g. 'USD'). When omitted, defaults to the merchant's primary currency."},
}

// initGetCostReportCmd initializes the get-cost-report command.
func initGetCostReportCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-cost-report",
		Short:   "Report",
		Long:    "Aggregate cost data across costs and customers with grouping, filtering, and time-series breakdown.",
		Example: "  paygentic costs get-cost-report --from 2025-03-21T13:37:39.948Z --to 2024-04-29T10:02:17.490Z --group-by cost",
		RunE:    runGetCostReportCmd,
		Aliases: []string{"gcr"},
	}
	flagutil.RegisterFlags(cmd, getCostReportCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetCostReportRequest](getCostReportCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-cost-report: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCostReportCmd executes the get-cost-report command.
func runGetCostReportCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getCostReportCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getCostReportCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetCostReportRequest](cmd, getCostReportCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Costs.GetCostReport(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
