// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package costs

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getCostSummaryCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "The unique identifier of the cost [required]"},
	{FlagName: "subject", Shorthand: "s", FieldPath: "Subject", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter usage to a specific subject (billing entity). When provided, only cost events matching this subject are included. When omitted, usage is aggregated across all subjects for the merchant."},
	{FlagName: "from", FieldPath: "From", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Start of the query window (ISO 8601). Required together with 'to'. [required]"},
	{FlagName: "to", Shorthand: "t", FieldPath: "To", Kind: flagutil.FlagKindDateTime, Required: true, Description: "End of the query window (ISO 8601). Required together with 'from'. [required]"},
	{FlagName: "group-by", Shorthand: "g", FieldPath: "GroupBy", Kind: flagutil.FlagKindString, Optional: true, Description: "Comma-separated dimension keys to group results by."},
	{FlagName: "window", Shorthand: "w", FieldPath: "Window", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"MINUTE", "HOUR", "DAY"}, Description: "Time window granularity for time-series breakdown. (options: MINUTE, HOUR, DAY)"},
	{FlagName: "filter-group-by", FieldPath: "FilterGroupBy", Kind: flagutil.FlagKindString, Optional: true, Description: "JSON-encoded dimension filter (e.g. {\"model\":\"gpt-4\",\"region\":\"us-east\"}). Keys must match those defined in the cost's groupBy configuration. Retrieve the cost first to determine valid keys."},
}

// initGetCostSummaryCmd initializes the get-cost-summary command.
func initGetCostSummaryCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get-cost-summary",
		Short:   "Query Summary",
		Long:    "Query usage data and compute cost for a specific cost configuration. To retrieve summaries for all costs belonging to a merchant, first call listCosts to obtain cost IDs, then call this endpoint in parallel for each ID.",
		Example: "  paygentic costs get-cost-summary --id <id> --from 2024-06-26T21:12:15.723Z --to 2026-01-05T23:33:29.000Z",
		RunE:    runGetCostSummaryCmd,
		Aliases: []string{"gcs"},
	}
	flagutil.RegisterFlags(cmd, getCostSummaryCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetCostSummaryRequest](getCostSummaryCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-cost-summary: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetCostSummaryCmd executes the get-cost-summary command.
func runGetCostSummaryCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getCostSummaryCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getCostSummaryCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetCostSummaryRequest](cmd, getCostSummaryCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Costs.GetCostSummary(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
