// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 8fe78c9b38ec

package customers

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitCustomersRoot(parent *cobra.Command) error {
	var CustomersCmd = &cobra.Command{
		Use:   "customers",
		Short: "A `Customer` is an entity connected to a `Merchant` via a `Subscription`",
		Long:  "A `Customer` is an entity connected to a `Merchant` via a `Subscription`. This represents the merchant-facing perspective of `Consumers` who purchase their `Products`.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(CustomersCmd); err != nil {
		return err
	}

	if err := initCreateCmd(CustomersCmd); err != nil {
		return err
	}

	if err := initGetCmd(CustomersCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(CustomersCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(CustomersCmd); err != nil {
		return err
	}

	parent.AddCommand(CustomersCmd)
	return nil
}
