// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c2de65742054

package prices

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "billable-metric-id", FieldPath: "BillableMetricID", Kind: flagutil.FlagKindString, Optional: true, Description: "Unique identifier for a billable metric"},
	{FlagName: "fee-id", FieldPath: "FeeID", Kind: flagutil.FlagKindString, Optional: true, Description: "The unique identifier for the fee referred to by this price. Either billableMetricId or feeId must be provided."},
	{FlagName: "pricing-unit-id", FieldPath: "PricingUnitID", Kind: flagutil.FlagKindString, Optional: true, Description: "Unique identifier for a pricing unit"},
	{FlagName: "model", Shorthand: "m", FieldPath: "Model", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"standard", "volume"}, Description: "Pricing calculation model. Required for billable metrics, optional for fees (defaults to 'standard'). 'standard' and 'volume' are accepted; fees only support 'standard'. For percentage/revenue-share use 'standard' with a unit-price multiplier. Legacy prices using 'dynamic'/'percentage' stay readable and billable but cannot be created. (options: standard, volume)"},
	{FlagName: "invoice-display-name", FieldPath: "InvoiceDisplayName", Kind: flagutil.FlagKindString, Required: true, Description: "Line item label shown on customer invoices. Sample values: 'Claude Token Consumption', 'Storage Usage (GB)', 'Inference API Calls', 'Image Generation Count', 'Training Compute Hours', 'Data Transfer (TB)' [required]"},
	{FlagName: "invoice-display-group", FieldPath: "InvoiceDisplayGroup", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"invoiceDisplayGroup,omitempty"`, Description: "Presentation only. Prices sharing this value, within one billing period, print as a single row on the rendered invoice PDF and are described by this string. Every member still bills its own line item on the ledger, this API and the compliance document. The combined row's rate is derived from the members' own rates. Requires the 'standard' pricing model. Sample values: 'Cross Border Fees', 'FX Fees'"},
	{FlagName: "payment-term", FieldPath: "PaymentTerm", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"in_arrears", "in_advance"}, Description: "Billing timing preference: 'in_advance' (prepaid — charged upfront or drawn from a prepaid commitment) or 'in_arrears' (charged at period end). (options: in_arrears, in_advance) [required]"},
	{FlagName: "billing-cadence", FieldPath: "BillingCadence", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"billingCadence,omitempty"`, Description: "ISO 8601 duration for recurring charges (e.g., 'P1M' for monthly, 'P1Y' for yearly) or 'P0D' for one-time charges. Required for fees, optional for billable metrics. Sample values: 'P0D' for one-time, 'P1M' for monthly recurring, 'P1Y' for yearly recurring"},
	{FlagName: "properties", FieldPath: "Properties", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, TypeDescription: "JSON value (one of: { unitPrice: string } | { maxPrice: string, minPrice: string } | { tiers: object[] } | { maxCharge: string, minCharge: string, percentage: string })"}},
	{FlagName: "feature", FieldPath: "Feature", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"feature,omitempty"`, Description: "JSON object"},
	{FlagName: "grant-discount-enabled", Shorthand: "g", FieldPath: "GrantDiscountEnabled", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices."},
	{FlagName: "is-obligation", FieldPath: "IsObligation", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "A fixed amount owed whole rather than a per-period rate. An obligation is not prorated over a partial first period: when a subscription starts before its billing anchor, no truncated stub is billed and the first charge is the full amount at the next anchor. An obligation also refuses an interval boundary that falls strictly inside one of its own billing periods, since part of an amount owed whole is not a thing to bill. Defaults to false, which is a rate and is today's behaviour for every price. Not supported on a metered price, whose amount resolves from usage at close."},
	{FlagName: "rate-type", Shorthand: "r", FieldPath: "RateType", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"amount", "proportion"}, Description: "What properties.unitPrice is denominated in. 'amount' (the default) is an amount of the invoice currency for each unit metered, so the quantity is the multiplier. 'proportion' is the reverse: a dimensionless share of a currency-denominated quantity, so '0.02' is 2% and the invoice prints '2.00%'. Presentation only. Requires a standard metered price in real currency. (options: amount, proportion)"},
	{FlagName: "tax", Shorthand: "t", FieldPath: "Tax", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"tax,omitempty"`, Description: "A price's tax declaration. Optional on write — a price that declares nothing is `IN_SCOPE`, and is billed and taxed exactly as it was before this object existed. Always present on read. Replaced as a whole on update: send the object to change it, omit it to leave it alone."},
	{FlagName: "quantity", FieldPath: "Quantity", Kind: flagutil.FlagKindInt64, Optional: true, Description: "Quantity for invoice line items. Total per period = quantity × unitPrice. Only supported for fee prices; metered prices derive quantity from usage. Defaults to 1."},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create",
		Long:    "Create",
		Example: "  paygentic prices create --invoice-display-name <value> --payment-term in_arrears --properties '{\"maxPrice\":\"<value>\",\"minPrice\":\"<value>\"}'",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreatePriceRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.CreatePriceRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prices.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
