// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c2de65742054

package prices

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createCmdMeta = []flagutil.FlagMeta{
	{FlagName: "billable-metric-id", FieldPath: "BillableMetricID", Kind: flagutil.FlagKindString, Optional: true, Description: "Unique identifier for a billable metric"},
	{FlagName: "fee-id", FieldPath: "FeeID", Kind: flagutil.FlagKindString, Optional: true, Description: "The unique identifier for the fee referred to by this price. Either billableMetricId or feeId must be provided."},
	{FlagName: "model", Shorthand: "m", FieldPath: "Model", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"standard", "dynamic", "volume", "percentage"}, Description: "Pricing calculation model. Required for billable metrics, optional for fees (defaults to 'standard'). (options: standard, dynamic, volume, percentage)"},
	{FlagName: "invoice-display-name", Shorthand: "i", FieldPath: "InvoiceDisplayName", Kind: flagutil.FlagKindString, Required: true, Description: "Line item label shown on customer invoices. Sample values: 'Claude Token Consumption', 'Storage Usage (GB)', 'Inference API Calls', 'Image Generation Count', 'Training Compute Hours', 'Data Transfer (TB)' [required]"},
	{FlagName: "payment-term", FieldPath: "PaymentTerm", Kind: flagutil.FlagKindEnum, Required: true, EnumValues: []string{"instant", "in_arrears", "in_advance"}, Description: "Billing timing preference. For billable metrics: 'instant' (charges immediately) or 'in_arrears' (charges at period end). For fees: 'in_advance' (charges upfront) or 'in_arrears' (charges at period end). (options: instant, in_arrears, in_advance) [required]"},
	{FlagName: "billing-cadence", FieldPath: "BillingCadence", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"billingCadence,omitempty"`, Description: "ISO 8601 duration for recurring charges (e.g., 'P1M' for monthly, 'P1Y' for yearly) or 'P0D' for one-time charges. Required for fees, optional for billable metrics. Sample values: 'P0D' for one-time, 'P1M' for monthly recurring, 'P1Y' for yearly recurring"},
	{FlagName: "properties", FieldPath: "Properties", Kind: flagutil.FlagKindUnion, Union: &flagutil.UnionMeta{Discriminated: false, TypeDescription: "JSON value (one of: { unitPrice: string } | { maxPrice: string, minPrice: string } | { default: string, parameters: object } | { maxCharge: string, minCharge: string, percentage: string })"}},
	{FlagName: "feature", FieldPath: "Feature", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"feature,omitempty"`, Description: "JSON object"},
	{FlagName: "grant-discount-enabled", Shorthand: "g", FieldPath: "GrantDiscountEnabled", Kind: flagutil.FlagKindBool, Optional: true, HasDefault: true, Description: "When true, grants applied to a subscription will discount usage charged by this price. Only supported for standard metered prices."},
}

// initCreateCmd initializes the create command.
func initCreateCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create",
		Long:    "Create",
		Example: "  paygentic prices create --invoice-display-name <value> --payment-term instant --properties '{\"default\":\"<value>\",\"parameters\":{\"function\":\"linear\",\"gradient\":\"<value>\",\"max\":\"<value>\",\"min\":\"<value>\"} }'",
		RunE:    runCreateCmd,
	}
	flagutil.RegisterFlags(cmd, createCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreatePriceRequest](createCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateCmd executes the create command.
func runCreateCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[operations.CreatePriceRequest](cmd, createCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Prices.Create(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
