// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d4736b901147

package orders

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createOrderLineItemCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "item-id", Shorthand: "i", FieldPath: "Body.ItemID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"itemId,omitempty"`, Description: "string value"},
	{FlagName: "description", FieldPath: "Body.Description", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"description,omitempty"`, Description: "string value"},
	{FlagName: "quantity", FieldPath: "Body.Quantity", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "list-unit-price", Shorthand: "l", FieldPath: "Body.ListUnitPrice", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "discount-unit-amount", FieldPath: "Body.DiscountUnitAmount", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "unit-price", Shorthand: "u", FieldPath: "Body.UnitPrice", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "total-price", FieldPath: "Body.TotalPrice", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "metadata", Shorthand: "m", FieldPath: "Body.Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "value"},
	{FlagName: "term-start-date", FieldPath: "Body.TermStartDate", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "term-end-date", FieldPath: "Body.TermEndDate", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
}

// initCreateOrderLineItemCmd initializes the create-order-line-item command.
func initCreateOrderLineItemCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create-order-line-item",
		Short:   "Add a line item",
		Long:    "Add a line item",
		Example: "  paygentic orders create-order-line-item --order-id <id> --quantity <value> --list-unit-price <value> --unit-price <value> --total-price <value>",
		RunE:    runCreateOrderLineItemCmd,
		Aliases: []string{"coli"},
	}
	flagutil.RegisterFlags(cmd, createOrderLineItemCmdMeta)
	if err := flagutil.ValidateMeta[operations.CreateOrderLineItemRequest](createOrderLineItemCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-order-line-item: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateOrderLineItemCmd executes the create-order-line-item command.
func runCreateOrderLineItemCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createOrderLineItemCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createOrderLineItemCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.CreateOrderLineItemRequest](cmd, createOrderLineItemCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Orders.CreateOrderLineItem(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
