// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 08903072bd64

package orders

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var deleteOrderLineItemCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
}

// initDeleteOrderLineItemCmd initializes the delete-order-line-item command.
func initDeleteOrderLineItemCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "delete-order-line-item",
		Short:   "Delete a line item",
		Long:    "Delete a line item",
		Example: "  paygentic orders delete-order-line-item --order-id <id> --id <id>",
		RunE:    runDeleteOrderLineItemCmd,
		Aliases: []string{"doli"},
	}
	flagutil.RegisterFlags(cmd, deleteOrderLineItemCmdMeta)
	if err := flagutil.ValidateMeta[operations.DeleteOrderLineItemRequest](deleteOrderLineItemCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for delete-order-line-item: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runDeleteOrderLineItemCmd executes the delete-order-line-item command.
func runDeleteOrderLineItemCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, deleteOrderLineItemCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, deleteOrderLineItemCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.DeleteOrderLineItemRequest](cmd, deleteOrderLineItemCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Orders.DeleteOrderLineItem(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
