// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d0eac5f8de20

package orders

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var updateOrderCmdMeta = []flagutil.FlagMeta{
	{FlagName: "id", Shorthand: "i", FieldPath: "ID", Kind: flagutil.FlagKindString, Required: true, Description: "[required]"},
	{FlagName: "type", FieldPath: "Body.Type", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"type,omitempty"`, Description: "options: new_business, renewal, expansion"},
	{FlagName: "term-start-date", FieldPath: "Body.TermStartDate", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "term-end-date", FieldPath: "Body.TermEndDate", Kind: flagutil.FlagKindDateTime, Optional: true, Description: "date/time value"},
	{FlagName: "close-date", FieldPath: "Body.CloseDate", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"closeDate,omitempty"`, Description: "date/time value"},
	{FlagName: "total-amount", FieldPath: "Body.TotalAmount", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "default-payment-term-days", FieldPath: "Body.DefaultPaymentTermDays", Kind: flagutil.FlagKindInt64, Optional: true, Description: "integer value"},
	{FlagName: "metadata", Shorthand: "m", FieldPath: "Body.Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "value"},
	{FlagName: "cancelled-at", FieldPath: "Body.CancelledAt", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"cancelledAt,omitempty"`, Description: "date/time value"},
	{FlagName: "reseller-id", Shorthand: "r", FieldPath: "Body.ResellerID", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"resellerId,omitempty"`, Description: "string value"},
	{FlagName: "tax-exempt", FieldPath: "Body.TaxExempt", Kind: flagutil.FlagKindBool, Optional: true, Description: "boolean flag"},
	{FlagName: "selling-entity", Shorthand: "s", FieldPath: "Body.SellingEntity", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"sellingEntity,omitempty"`, Description: "string value"},
}

// initUpdateOrderCmd initializes the update-order command.
func initUpdateOrderCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "update",
		Short:   "Update an order",
		Long:    "Update an order",
		Example: "  paygentic orders update --id <id>",
		RunE:    runUpdateOrderCmd,
	}
	flagutil.RegisterFlags(cmd, updateOrderCmdMeta)
	if err := flagutil.ValidateMeta[operations.UpdateOrderRequest](updateOrderCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for update-order: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runUpdateOrderCmd executes the update-order command.
func runUpdateOrderCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, updateOrderCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, updateOrderCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.UpdateOrderRequest](cmd, updateOrderCmdMeta, "Body", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Orders.UpdateOrder(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
