// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: a39704729a6c

package merchants

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitMerchantsRoot(parent *cobra.Command) error {
	var MerchantsCmd = &cobra.Command{
		Use:   "merchants",
		Short: "Operations for merchants",
		Long:  "Operations for merchants",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initResetCmd(MerchantsCmd); err != nil {
		return err
	}

	parent.AddCommand(MerchantsCmd)
	return nil
}
