// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: d4210e1b34b1

package components

// InvoicePaymentProvider - The payment provider that a hosted payment link routes to.
type InvoicePaymentProvider string

const (
	InvoicePaymentProviderStripe    InvoicePaymentProvider = "stripe"
	InvoicePaymentProviderAirwallex InvoicePaymentProvider = "airwallex"
)

func (e InvoicePaymentProvider) ToPointer() *InvoicePaymentProvider {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *InvoicePaymentProvider) IsExact() bool {
	if e != nil {
		switch *e {
		case "stripe", "airwallex":
			return true
		}
	}
	return false
}
