// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: f2d211d4040c

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
)

// RetryPaymentResponseObject - The object type
type RetryPaymentResponseObject string

const (
	RetryPaymentResponseObjectRetryPaymentResult RetryPaymentResponseObject = "retry_payment_result"
)

func (e RetryPaymentResponseObject) ToPointer() *RetryPaymentResponseObject {
	return &e
}
func (e *RetryPaymentResponseObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "retry_payment_result":
		*e = RetryPaymentResponseObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetryPaymentResponseObject: %v", v)
	}
}

// RetryPaymentResponse - The result of a payment retry. Every response status of the retry operation that is not an error envelope uses this shape.
type RetryPaymentResponse struct {
	// The object type
	Object RetryPaymentResponseObject `json:"object"`
	// True only when the charge succeeded or no amount is unpaid. The response status is 200 only when this is true.
	Success bool `json:"success"`
	// The invoice ID
	InvoiceID string `json:"invoiceId"`
	// The provider's payment reference for the charge, when the provider has one.
	PaymentIntentID *string `json:"paymentIntentId,omitzero"`
	// Why a payment retry did not collect the money.
	Error *RetryPaymentError `json:"error,omitzero"`
}

func (r RetryPaymentResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetryPaymentResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RetryPaymentResponse) GetObject() RetryPaymentResponseObject {
	if r == nil {
		return RetryPaymentResponseObject("")
	}
	return r.Object
}

func (r *RetryPaymentResponse) GetSuccess() bool {
	if r == nil {
		return false
	}
	return r.Success
}

func (r *RetryPaymentResponse) GetInvoiceID() string {
	if r == nil {
		return ""
	}
	return r.InvoiceID
}

func (r *RetryPaymentResponse) GetPaymentIntentID() *string {
	if r == nil {
		return nil
	}
	return r.PaymentIntentID
}

func (r *RetryPaymentResponse) GetError() *RetryPaymentError {
	if r == nil {
		return nil
	}
	return r.Error
}
