// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c78d7481264b

package components

// RetryPaymentError - Why a payment retry did not collect the money.
type RetryPaymentError struct {
	// Human-readable message. Do not parse it; use `code`.
	Message string `json:"message"`
	// Error category, for example `card_error` or `processing`.
	Type *string `json:"type,omitzero"`
	// Machine-readable reason. See the operation description for the values.
	Code *string `json:"code,omitzero"`
	// The card decline code from the provider, when one is available.
	DeclineCode *string `json:"declineCode,omitzero"`
}

func (r *RetryPaymentError) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

func (r *RetryPaymentError) GetType() *string {
	if r == nil {
		return nil
	}
	return r.Type
}

func (r *RetryPaymentError) GetCode() *string {
	if r == nil {
		return nil
	}
	return r.Code
}

func (r *RetryPaymentError) GetDeclineCode() *string {
	if r == nil {
		return nil
	}
	return r.DeclineCode
}
