// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2943c8f6650a

package components

import (
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
	"time"
)

type RevenueTrendBucket struct {
	// Start time of this bucket
	Timestamp time.Time `json:"timestamp"`
	// Revenue for this bucket, computed exactly as netRevenue: invoices issued in the bucket (on periodBasis=billingPeriod, lines billing it), excluding tax, less refunds issued in it, excluding tax. The buckets sum to netRevenue.
	Revenue string `json:"revenue"`
	// Total amount of all invoices issued in this bucket (all statuses, by issuedAt), excluding tax, before refunds. Revenue is the revenue field.
	IssuedInvoices string `json:"issuedInvoices"`
	// Amount of written-off invoices in dollars for this bucket (by writtenOffAt)
	WrittenOffInvoices string `json:"writtenOffInvoices"`
	// Completed payment-link payments in dollars for this bucket, reported beside revenue, not in it
	CompletedPayments string `json:"completedPayments"`
	// Gross magnitude of usage-scaled rebates (negative metered line items) on invoices issued in this bucket, in dollars. Netted into issuedInvoices; surfaced here for visibility.
	Rebates string `json:"rebates"`
	// Per-group trend entries (present when groupBy=plan or groupBy=customer)
	GroupBreakdown []GroupTrendEntry `json:"groupBreakdown,omitzero"`
}

func (r RevenueTrendBucket) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RevenueTrendBucket) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (r *RevenueTrendBucket) GetTimestamp() time.Time {
	if r == nil {
		return time.Time{}
	}
	return r.Timestamp
}

func (r *RevenueTrendBucket) GetRevenue() string {
	if r == nil {
		return ""
	}
	return r.Revenue
}

func (r *RevenueTrendBucket) GetIssuedInvoices() string {
	if r == nil {
		return ""
	}
	return r.IssuedInvoices
}

func (r *RevenueTrendBucket) GetWrittenOffInvoices() string {
	if r == nil {
		return ""
	}
	return r.WrittenOffInvoices
}

func (r *RevenueTrendBucket) GetCompletedPayments() string {
	if r == nil {
		return ""
	}
	return r.CompletedPayments
}

func (r *RevenueTrendBucket) GetRebates() string {
	if r == nil {
		return ""
	}
	return r.Rebates
}

func (r *RevenueTrendBucket) GetGroupBreakdown() []GroupTrendEntry {
	if r == nil {
		return nil
	}
	return r.GroupBreakdown
}
