// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 9b5deae7c3fc

package components

type SubscriptionIntervalRemoveOp struct {
	// The interval being removed.
	ID string `json:"id"`
}

func (s *SubscriptionIntervalRemoveOp) GetID() string {
	if s == nil {
		return ""
	}
	return s.ID
}
