// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: c08deb2397b9

package components

import (
	"encoding/json"
	"fmt"
	"github.com/paygentic/cli/internal/sdk/sdkinternal/utils"
	"time"
)

// WebhookPortalObject - Object type identifier
type WebhookPortalObject string

const (
	WebhookPortalObjectWebhookPortal WebhookPortalObject = "webhookPortal"
)

func (e WebhookPortalObject) ToPointer() *WebhookPortalObject {
	return &e
}
func (e *WebhookPortalObject) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "webhookPortal":
		*e = WebhookPortalObject(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WebhookPortalObject: %v", v)
	}
}

type WebhookPortal struct {
	// Object type identifier
	Object WebhookPortalObject `json:"object"`
	// When the portal link expires
	ExpiresAt time.Time `json:"expiresAt"`
	// Magic link URL to access the webhook portal
	URL string `json:"url"`
}

func (w WebhookPortal) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebhookPortal) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (w *WebhookPortal) GetObject() WebhookPortalObject {
	if w == nil {
		return WebhookPortalObject("")
	}
	return w.Object
}

func (w *WebhookPortal) GetExpiresAt() time.Time {
	if w == nil {
		return time.Time{}
	}
	return w.ExpiresAt
}

func (w *WebhookPortal) GetURL() string {
	if w == nil {
		return ""
	}
	return w.URL
}
