// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: acf703e448d7

package features

import (
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

func InitFeaturesRoot(parent *cobra.Command) error {
	var FeaturesCmd = &cobra.Command{
		Use:   "features",
		Short: "A `Feature` represents a specific capability or functionality provided by a `Product`",
		Long:  "A `Feature` represents a specific capability or functionality provided by a `Product`. Features can be metered (usage-based), static (fixed allocation), or boolean (enabled/disabled).",
		RunE: func(cmd *cobra.Command, args []string) error {
			if usage.UsageRequested(cmd) {
				return usage.EmitSchema(cmd, cmd.OutOrStdout())
			}
			return cmd.Help()
		},
	}

	if err := initListCmd(FeaturesCmd); err != nil {
		return err
	}

	if err := initCreateCmd(FeaturesCmd); err != nil {
		return err
	}

	if err := initGetCmd(FeaturesCmd); err != nil {
		return err
	}

	if err := initUpdateCmd(FeaturesCmd); err != nil {
		return err
	}

	if err := initDeleteCmd(FeaturesCmd); err != nil {
		return err
	}

	parent.AddCommand(FeaturesCmd)
	return nil
}
