// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 2e101a43dec8

package profitability

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var getProfitabilityCmdMeta = []flagutil.FlagMeta{
	{FlagName: "merchant-id", Shorthand: "m", FieldPath: "MerchantID", Kind: flagutil.FlagKindString, Required: true, Description: "Merchant whose customers to summarize [required]"},
	{FlagName: "from", Shorthand: "f", FieldPath: "From", Kind: flagutil.FlagKindDateTime, Required: true, Description: "Start of the time range (ISO 8601 format) [required]"},
	{FlagName: "to", FieldPath: "To", Kind: flagutil.FlagKindDateTime, Required: true, Description: "End of the time range (ISO 8601 format) [required]"},
	{FlagName: "top-n", FieldPath: "TopN", Kind: flagutil.FlagKindInt64, Optional: true, HasDefault: true, DefaultInt: 10, Description: "Number of top customers (by profit) to return individually. The rest are rolled into a single 'Other' row."},
	{FlagName: "currency", Shorthand: "c", FieldPath: "Currency", Kind: flagutil.FlagKindString, Optional: true, Description: "ISO 4217 currency code to scope the summary. Defaults to the merchant's primary currency."},
	{FlagName: "bucket-width", Shorthand: "b", FieldPath: "BucketWidth", Kind: flagutil.FlagKindEnum, Optional: true, HasDefault: true, DefaultStr: "day", EnumValues: []string{"hour", "day", "week"}, Description: "Time bucket granularity for the per-customer revenue trend. When omitted, the server picks a reasonable bucket from the window length. (options: hour, day, week)"},
}

// initGetProfitabilityCmd initializes the get-profitability command.
func initGetProfitabilityCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "get",
		Short:   "Get profitability summary",
		Long:    "Returns a per-customer profitability summary for a merchant over a date range. Each row aggregates revenue (from issued + paid invoices), cost (from metered cost discovery), profit, and margin. Customers are ranked by profit descending and capped at topN; the remainder is rolled into a single self-consistent 'Other' row whose revenue, cost, and profit reflect the same set of customers. Rows are inner-joined against the merchant's customer list, so orphaned meter subjects from deleted or unknown customers are dropped.",
		Example: "  paygentic profitability get --merchant-id <id> --from 2026-09-10T15:32:06.535Z --to 2026-10-20T08:45:45.521Z",
		RunE:    runGetProfitabilityCmd,
	}
	flagutil.RegisterFlags(cmd, getProfitabilityCmdMeta)
	if err := flagutil.ValidateMeta[operations.GetProfitabilityRequest](getProfitabilityCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for get-profitability: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runGetProfitabilityCmd executes the get-profitability command.
func runGetProfitabilityCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, getProfitabilityCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, getProfitabilityCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.GetProfitabilityRequest](cmd, getProfitabilityCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.Profitability.GetProfitability(cmd.Context(), *req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
