// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: e0d832c11534

package billingschedules

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/components"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var createBillingScheduleCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "subscription-id", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "string value"},
	{FlagName: "start-date", FieldPath: "StartDate", Kind: flagutil.FlagKindDateTime, Required: true, Description: "[required]"},
	{FlagName: "end-date", Shorthand: "e", FieldPath: "EndDate", Kind: flagutil.FlagKindDateTime, Required: true, Description: "[required]"},
	{FlagName: "billing-anchor", Shorthand: "b", FieldPath: "BillingAnchor", Kind: flagutil.FlagKindDateTime, Required: true, Description: "[required]"},
	{FlagName: "alignment-policy", Shorthand: "a", FieldPath: "AlignmentPolicy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"anchor", "calendar", "coterm"}, Description: "options: anchor, calendar, coterm"},
	{FlagName: "proration-policy", FieldPath: "ProrationPolicy", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"none", "daily"}, Description: "options: none, daily"},
	{FlagName: "payment-term-days", FieldPath: "PaymentTermDays", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"paymentTermDays,omitempty"`, Description: "integer value"},
	{FlagName: "period-preset", FieldPath: "PeriodPreset", Kind: flagutil.FlagKindEnum, Optional: true, EnumValues: []string{"single", "P1M", "P3M", "P6M", "P1Y", "custom"}, Description: "options: single, P1M, P3M, P6M, P1Y, custom"},
	{FlagName: "custom-period-windows", Shorthand: "c", FieldPath: "CustomPeriodWindows", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"customPeriodWindows,omitempty"`, Description: "list of values"},
	{FlagName: "metadata", Shorthand: "m", FieldPath: "Metadata", Kind: flagutil.FlagKindJSON, Optional: true, Annotations: `json:"metadata,omitempty"`, Description: "value"},
}

// initCreateBillingScheduleCmd initializes the create-billing-schedule command.
func initCreateBillingScheduleCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "create",
		Short:   "Create a billing schedule",
		Long:    "Create a billing schedule",
		Example: "  paygentic billing-schedules create --start-date 2025-12-16T18:30:43.578Z --end-date 2024-09-07T07:24:23.517Z --billing-anchor 2025-10-01T16:17:23.367Z",
		RunE:    runCreateBillingScheduleCmd,
	}
	flagutil.RegisterFlags(cmd, createBillingScheduleCmdMeta)
	if err := flagutil.ValidateMeta[components.CreateBillingScheduleRequest](createBillingScheduleCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for create-billing-schedule: %w", err)
	}
	cmd.Flags().String("body", "", "Request body as JSON (alternative to individual flags). Can also be provided via stdin.")
	parent.AddCommand(cmd)
	return nil
}

// runCreateBillingScheduleCmd executes the create-billing-schedule command.
func runCreateBillingScheduleCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, createBillingScheduleCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, createBillingScheduleCmdMeta); err != nil {
			return err
		}
	}
	request, err := flagutil.BuildRequest[components.CreateBillingScheduleRequest](cmd, createBillingScheduleCmdMeta, "", "body")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.BillingSchedules.CreateBillingSchedule(cmd.Context(), *request, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
