// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
// @generated-id: 584695711aa9

package billingschedules

import (
	"fmt"
	"github.com/paygentic/cli/internal/client"
	"github.com/paygentic/cli/internal/flagutil"
	"github.com/paygentic/cli/internal/interactive"
	"github.com/paygentic/cli/internal/output"
	"github.com/paygentic/cli/internal/sdk"
	"github.com/paygentic/cli/internal/sdk/models/operations"
	"github.com/paygentic/cli/internal/usage"
	"github.com/spf13/cobra"
)

var listBillingSchedulesCmdMeta = []flagutil.FlagMeta{
	{FlagName: "order-id", FieldPath: "OrderID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by owning order (XOR with subscriptionId)"},
	{FlagName: "subscription-id", Shorthand: "s", FieldPath: "SubscriptionID", Kind: flagutil.FlagKindString, Optional: true, Description: "Filter by owning subscription (XOR with orderId)"},
}

// initListBillingSchedulesCmd initializes the list-billing-schedules command.
func initListBillingSchedulesCmd(parent *cobra.Command) error {
	var cmd = &cobra.Command{
		Use:     "list",
		Short:   "List billing schedules",
		Long:    "List billing schedules",
		Example: "  paygentic billing-schedules list",
		RunE:    runListBillingSchedulesCmd,
	}
	flagutil.RegisterFlags(cmd, listBillingSchedulesCmdMeta)
	if err := flagutil.ValidateMeta[operations.ListBillingSchedulesRequest](listBillingSchedulesCmdMeta); err != nil {
		return fmt.Errorf("invalid metadata for list-billing-schedules: %w", err)
	}
	parent.AddCommand(cmd)
	return nil
}

// runListBillingSchedulesCmd executes the list-billing-schedules command.
func runListBillingSchedulesCmd(cmd *cobra.Command, args []string) error {
	if usage.UsageRequested(cmd) {
		return usage.EmitSchema(cmd, cmd.OutOrStdout())
	}
	if interactive.ShouldPrompt(cmd, listBillingSchedulesCmdMeta) {
		if err := interactive.PromptAndSetFlags(cmd, listBillingSchedulesCmdMeta); err != nil {
			return err
		}
	}
	req, err := flagutil.BuildRequest[operations.ListBillingSchedulesRequest](cmd, listBillingSchedulesCmdMeta, "", "")
	if err != nil {
		return err
	}
	s, err := client.NewClient(cmd)
	if err != nil {
		return err
	}
	sdkOpts, err := output.PrepareCallOpts(cmd)
	if err != nil {
		return err
	}
	// Dry-run: force skip deserialization so the synthetic empty response
	// does not cause parse failures in typed response handling.
	if client.IsDryRun(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	if err := output.ValidateGlobalServerIndex(cmd, len(sdk.ServerList)); err != nil {
		return err
	}
	if output.WantsRawJSON(cmd) {
		sdkOpts = append(sdkOpts, operations.WithSkipDeserialization())
	}
	res, err := s.BillingSchedules.ListBillingSchedules(cmd.Context(), req, sdkOpts...)
	if err != nil {
		return output.Error(cmd, err)
	}

	if err := output.Result(cmd, res); err != nil {
		return err
	}
	return nil
}
